### ISSUE TITLE
Unknown people on info page

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#596]
If a chapter has more than 4 organizers, the app usually displays unknown for couple of them. 

It is probably be caused by excessive amount of Api calls. Should be avoided by caching. There maybe a problem with caching.

**Comment by tasomaniac** [comment]
Just an observation. When I go offline, I see that it is cached and the info page loads completely fine. We have cache. But we have a problem.

**Comment by friedger** [comment]
We could use the GMS Plus API here, this allows to call for all organizers in one go

**Comment by tasomaniac** [comment]
We are requesting them again here even though we have them in cache. I think solving that will also be useful. 

We can use GMS Plus API but I don't like using 2 different things. I want to unify all Plus People related things.

**Comment by friedger** [comment]
fixed by #609

**Comment by tasomaniac** [comment]
This is also related to #693 and #694 
The problem still existed, this PR will probably improve it more.
